NOTIFICATION_CATEGORY_LOADED = @"NOTIFICATION_CATEGORY_LOADED"
NOTIFICATION_ENTRY_LOADED = @"NOTIFICATION_ENTRY_LOADED"
NOTIFICATION_HEADLINE_LOADED = @"NOTIFICATION_HEADLINE_LOADED"
NOTIFICATION_HEADLINE_SELECTED = @"NOTIFICATION_HEADLINE_SELECTED"
